#ifndef CATCH_GAME_POSITION_LIMITS_H
#define CATCH_GAME_POSITION_LIMITS_H

#define LEFT_LIMIT_POSITION_IN_PERCENT ((float)0.0f)
#define RIGHT_LIMIT_POSITION_IN_PERCENT ((float)100.0f)

#define UP_LIMIT_POSITION_IN_PERCENT ((float)100.0f)
#define DOWN_LIMIT_POSITION_IN_PERCENT ((float)0.0f)

#endif
